### ISSUE TITLE
Node name is sometimes array

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#697]
https://arax.ncats.io/?r=aa37ff6e-bbb7-44a7-89c3-6c868ea16b0b

Sometimes BTE will respond with a node in the knowledge graph which has an array for its name, which is invalid against TRAPI 1.4.

Should be an easy fix in the code that transforms internal KG->TRAPI KG.

**Comment by tokebe** [comment]
Should be addressed by https://github.com/biothings/bte_trapi_query_graph_handler/commit/9ae47c9d5409508f7d98ef2612090c604c7e16a7.

While it's likely this issue is isolated to new code on CI/Test, as I'm unable to verify it isn't happening on Prod, I'm leaving this issue open until the Prod deployment.

**Comment by colleenXu** [comment]
Duplicate or related to this? https://github.com/biothings/biothings_explorer/issues/693

**Comment by colleenXu** [comment]
A test based on the opening post example

<details><summary>basal insulin treats disease</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["UMLS:C0650607"],
                    "categories": ["biolink:Polypeptide", "biolink:Protein", "biolink:ChemicalEntity"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats"]
                }
            }
        }
    }
}
```

With the old code, the node would look like this: see the list name and lack of synonym value

```
                "UMLS:C0650607": {
                    "categories": [
                        "biolink:Protein"
                    ],
                    "name": [
                        "basal insulin",
                        "Basal insulin"
                    ],
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:xref",
                            "value": [
                                "UMLS:C0650607"
                            ]
                        },
                        {
                            "attribute_type_id": "biolink:synonym",
                            "value": []
                        }
                    ]
                },
```

After the latest commit, the node looks like this. The synonym value is still missing

```
                "UMLS:C0650607": {
                    "categories": [
                        "biolink:Protein"
                    ],
                    "name": "basal insulin",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:xref",
                            "value": [
                                "UMLS:C0650607"
                            ]
                        },
                        {
                            "attribute_type_id": "biolink:synonym",
                            "value": []
                        }
                    ]
                },
```

</details> 

@tokebe It looks like something is odd with the `biolink:synonym` node-attribute still...It's not the curie as default (the current behavior when SRI Node Norm doesn't give us anything for this field)

**Comment by colleenXu** [comment]
Note that @tokebe 's fix seems to be using only the first item of the list? VS my proposal in https://github.com/biothings/biothings_explorer/issues/693 was to concatenate the list strings...

**Comment by tokebe** [comment]
> @tokebe It looks like something is odd with the biolink:synonym node-attribute still...It's not the curie as default (the current behavior when SRI Node Norm doesn't give us anything for this field)

This appears to be a really strange case...SRI does return something, but it's missing most fields (we only get the primary ID, the same ID listed in equivalent IDs, and the type chain). Our code for using the curie only happens if SRI fails to resolve the entity, so it's never triggered. This might warrant some further discussion about how we'd like to handle such cases.

**Comment by tokebe** [comment]
Addressed by https://github.com/biothings/bte_trapi_query_graph_handler/commit/8f74254102f16326e88d5b59a25859401b4d47fd
