### ISSUE TITLE
migrate to Multiomics CTKP, remove other clinicaltrials.gov-based x-bte operations

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#861]
per @gglusman's [comment](https://github.com/NCATSTranslator/Feedback/issues/848#issuecomment-2321316434)

> The Plover CTKP will be available in ITRB/CI next Friday. (Sep 6)

Whenever this is ready and the SmartAPI record is updated (presumably [this one](https://smart-api.info/registry?q=e51073371d7049b9643e1edbdd61bcbd)), we should remove the `in_clinical_trials_for` edges based on ChEMBL and add CTKP.

**Comment by colleenXu** [comment]
**UPDATE: On Friday 9/20, I reverted these changes (commented out) so BTE would still use clinical trials data from MyChem + BioThings repoDB during the automated test run this weekend.** 

---

PREVIOUSLY...

I deployed the following changes on CI ([PR](https://github.com/biothings/bte-server/pull/42), [triggering deployment](https://github.com/biothings/biothings_explorer/commit/10a1bdb0c97153af6801bf6c7dfb33e5a274a4a2)): 
* add [Multiomics Clinical Trials KP](https://smart-api.info/ui/e51073371d7049b9643e1edbdd61bcbd) to BTE's config list
* use overrides to remove x-bte operations that use clinicaltrials.gov data https://github.com/NCATS-Tangerine/translator-api-registry/pull/157: 
    * MyChem's Chembl drug indications 
    * BioThings RepoDB's not-approved data 

**Note that Multiomics CTKP only has CI/dev instances right now. So BTE Test/Prod won't use it.**

I kept TTD's operations because it seems like they use a manual curation process that DOESN'T start with clinicaltrials.gov / AACT

<details><summary>Old notes on x-bte operations and clinical trials data</summary>
<p>

from [Translator Slack link](https://ncatstranslator.slack.com/archives/C014B3JAX36/p1719959814186439?thread_ts=1719867464.561699&cid=C014B3JAX36)

- TTD's data: I'm not sure, but it seems like there's a manual curation process that DOESN'T start with clinicaltrials.gov / AACT
- repoDB: seems to use AACT, finds drugs in terminated/withdrawn/suspended trials
- MyChem's data comes from Chembl drug indications

</p>
</details>

**Comment by colleenXu** [comment]
However, I see **multiple issues** using Multiomics CTKP:

1. **NO Disease/Pheno -> Chemical MetaEdges** in `meta_knowledge_graph` response ("reverses"). **This means BTE isn't calling this KP during MVP1/creative-treats queries**, where we start with a Disease ID. (AKA KP only has Chem ➡️ Disease/Pheno MetaEdges)
2. There are TRAPI validation errors coming from this KP's edge-attributes (lower-level orange?). Example: [main PK](https://arax.ci.transltr.io/?r=86496f30-46e7-471c-b130-1545d8f4bd60), look at BTE's response validation, "Error" section. 
    * unknown attribute_type_id: `biolink:supporting_study`. I'm also unsure of some of the nested attribute's type ids (not curies)...
    * unknown predicate `biolink:mentioned_in_trials_for` (see next point too) 
3. Some MetaEdges use the predicate `biolink:mentioned_in_trials_for`, **which isn't in biolink-model 4.2.2 so BTE won't use these MetaEdges when QEdge predicates are set** (BTE then consults the biolink-model predicate hierarchy and that term isn't there) 
4. Some MetaEdges use the node category `biolink:UNKNOWN`. Those MetaEdges are unusable.

**Comment by tokebe** [comment]
In order to better support CTKP we need to inject inverse operations as we parse their metakg. Proposed way of implementing this:

- Parse the API list entries for an `injectInverses` property
- When parsing operations, if the API has said property, attempt to generate a reverse operation
  - Flip subject/object, get inverse predicate, flip anything else that's necessary
  - If there is no inverse predicate, skip the operation for the purposes of inverse-injection

**Comment by colleenXu** [comment]
**UPDATE: On Friday 9/20, I reverted these changes (commented out) so BTE would still use clinical trials data from MyChem + BioThings repoDB during the automated test run this weekend.** 

Direct commit: https://github.com/biothings/bte-server/commit/b9e489bb58704b4165efc639820d4b82d5285f2b
Trigger deployment: https://github.com/biothings/biothings_explorer/commit/19a78d3fd5cca3bab8f87257d2b402c1f857e591

**Comment by gglusman** [comment]
>    * unknown attribute_type_id: `biolink:supporting_study`. I'm also unsure of some of the nested attribute's type ids (not curies)...

Modified it to the (existing) `biolink:supporting_study_metadata`.

>    * unknown predicate `biolink:mentioned_in_trials_for` (see next point too)

Pending inclusion in biolink.

> 4. Some MetaEdges use the node category `biolink:UNKNOWN`. Those MetaEdges are unusable.

There's currently just one node ("aging") with that erroneous category. Will fix.

**Comment by colleenXu** [comment]
Pasting from Slack: 

> Made some quick slides to illustrate my understanding of query direction / "inverting"/"reverses": https://docs.google.com/presentation/d/19PPPmkHEUStBUkEGBzVIGooB8hADHMBcoNRSmAsedYQ/edit?usp=sharing
> I imagine it'd be nice to support/keep supporting all 4 permutations of the query that I draw out,  but I dunno if that complicates things.

**Comment by colleenXu** [comment]
Example queries for CTKP (all return in <1s, should have less results to review): 

<details><summary>(1) Needs "reverse MetaEdge": Disease ID on object</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "ids": ["MONDO:0015243"],
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:in_clinical_trials_for"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(2) Needs "reverse MetaEdge": Disease ID on subject, flipped version of (1)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0015243"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:tested_by_clinical_trials_of"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(3) Uses original MetaEdge: Chemical ID on subject</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["PUBCHEM.COMPOUND:46871657"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:in_clinical_trials_for"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(4) Uses original MetaEdge: Chemical ID on object, flipped version of (3)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "ids": ["PUBCHEM.COMPOUND:46871657"],
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:tested_by_clinical_trials_of"]
                }
            }
        }
    }
}
```

</p>
</details>

**Comment by gglusman** [comment]
Finding suitable reverse predicates can be really hard. In this case, I find it strange to state that a disease/condition is being tested by a clinical trial of a drug. The drug is being tested, not the disease.
For another predicate in CTKP (mentioned_in_trials_for), the best I could come up with was "target_of_trial_mentioining"... which is still very cumbersome...

**Comment by colleenXu** [comment]
@gglusman 

For chem "mentioned in trials **for**" disease, maybe disease "mentioned in trials **of**" chem would work? or disease "mentioned in trials **with**" chem?

---

There are inverse predicates for all currently-existing predicates in the biolink model that should be used. But I agree that many of the new "treats" inverses have odd wording. 

I. In practice, BTE will format edges in its response to match the creative-mode query/query-edge direction (flipping them if necessary). This means the **inverse predicates won't show in the response for MVP1 creative-mode** (I dunno if this was one of your worries?). The "reverse" MetaEdges are just needed for BTE's internal MetaEdge representation and KP-querying process. 
2. I previously raised concerns about these inverse predicates' wording in DMs with Sierra (pasted below. I also buried some notes [here](https://github.com/biothings/biothings_explorer/issues/788#issuecomment-1972713233)). It may be worth bringing up your concerns with the inverse predicates with Sierra/in data-modeling...


> some of the new inverses sound a bit odd? (I took inspiration from the 4.1.3 inverse for `studied to treat`, which was `studied for treatment with`. That inverse is now `treated in studies with`)
> * "disease `tested by clinical trials of` drug". Maybe "studied in clinical trials with" (or for) sounds better?
> * "disease `tested by preclinical trials of` drug"
> * "disease `models demonstrating benefits for` drug". Maybe "models show benefit from" sounds better?
> * "disease `treatment applications from` drug". Hmm...the wording for this is tricky >.< (easier if the canonical predicate reworded to `reported to treat` , then it could be `reportedly treated with`)

**Comment by gglusman** [comment]
A thought: if inverse predicates are just an internal construct and never displayed to a human, the simplest and best way to construct them might be "inverse_of_[original_predicate]".

**Comment by gglusman** [comment]
> For chem "mentioned in trials **for**" disease, maybe disease "mentioned in trials **of**" chem would work? or disease "mentioned in trials **with**" chem?

Probably not, as the concept is asymmetric. We use the "mentioned" predicate when there is more than one intervention stated and it is not [yet] clear which one is being tested. Inverting it by saying that the disease is mentioned in a trial of one of those interventions would imply that the trial is indeed testing that intervention.

**Comment by colleenXu** [comment]
@gglusman 

disease "involved in trials that mention" chem then?

**Comment by gglusman** [comment]
> disease "involved in trials that mention" chem then?

That's quite similar to "target_of_trial_mentioining". :)

**Comment by colleenXu** [comment]
BTE could benefit from using the "reverse MetaEdge creation" on all new Multiomics TRAPI KPs, not just CTKP. 

@tokebe here's example queries for them. You can use the config here if it's helpful https://github.com/biothings/bte-server/pull/43

<details><summary>Drug Approvals</summary>
<p>

https://smart-api.info/ui/edc04feaf16c12424737988ce2e90d60

Also has Chem -> Disease MetaEdges

<details><summary>(1) Needs "reverse MetaEdge": Disease ID on object</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "ids": ["MONDO:0006014"],
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(2) Needs "reverse MetaEdge": Disease ID on subject, flipped version of (1)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0006014"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treated_by"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(3) Uses original MetaEdge: Chemical ID on subject</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["PUBCHEM.COMPOUND:46871657"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(4) Uses original MetaEdge: Chemical ID on object, flipped version of (3)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "ids": ["PUBCHEM.COMPOUND:46871657"],
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treated_by"]
                }
            }
        }
    }
}
```

</p>
</details> 

</p>
</details> 


<details><summary>Microbiome</summary>
<p>

https://smart-api.info/ui/a8be4ea3fe8fa80a952ead0b3c5e4bc1

Using BiologicalProcess -(correlated_with)-> SmallMolecule MetaEdge as reference. 

<details><summary>(1) Needs "reverse MetaEdge": SmallMolecule ID on object</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories":["biolink:BiologicalProcess"]
                },
                "n1": {
                    "ids":["PUBCHEM.COMPOUND:24749"],
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:correlated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(2) Needs "reverse MetaEdge": SmallMolecule ID on subject, flipped version of (1)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["PUBCHEM.COMPOUND:24749"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories":["biolink:BiologicalProcess"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:correlated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(3) Uses original MetaEdge: BiologicalProcess ID on subject</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["GO:0009106"],
                    "categories":["biolink:BiologicalProcess"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:correlated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(4) Uses original MetaEdge: BiologicalProcess ID on object, flipped version of (3)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "ids":["GO:0009106"],
                    "categories":["biolink:BiologicalProcess"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:correlated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

</p>
</details> 



<details><summary>Multiomics</summary>
<p>

https://smart-api.info/ui/1b6de23ed3c4e0713b20794477ba1e39

Using Protein -(associated_with)-> Disease / PhenotypicFeature MetaEdges as reference. 

<details><summary>(1) Needs "reverse MetaEdge": Disease ID on object</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories":["biolink:Protein"]
                },
                "n1": {
                    "ids":["MONDO:0005477"],
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:associated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(2) Needs "reverse MetaEdge": Disease ID on subject, flipped version of (1)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["MONDO:0005477"],
                    "categories": ["biolink:Disease"]

                },
                "n1": {
                    "categories":["biolink:Protein"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:associated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(3) Uses original MetaEdge: Protein ID on subject</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["UniProtKB:Q8NET8"],
                    "categories":["biolink:Protein"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:associated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

<details><summary>(4) Uses original MetaEdge: Protein ID on object, flipped version of (3)</summary>
<p>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "ids":["UniProtKB:Q8NET8"],
                    "categories":["biolink:Protein"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:associated_with"]
                }
            }
        }
    }
}
```

</p>
</details> 

</p>
</details>

**Comment by tokebe** [comment]
@colleenXu I've made PRs for the reverse-metaEdge injection behavior, see branches named `ctkp-reverse`

**Comment by colleenXu** [comment]
@tokebe 

YAY it all works! I tested...
* all 4 Multiomics TRAPIs with the example queries in earlier comments - looks like edges are being retrieved properly in all 4 query-flavors. 
* a MVP1 creative-mode: CTKP + DAKP (drug approvals) edges were successfully retrieved and showed up in the response

### But note!
* I didn't check if Multiomics TRAPIs can handle multiple input IDs on the same QNode (return edges for both input IDs properly). Did you @tokebe? 
* the logs on "created reverse metaEdges" are useful...but kinda a lot. And they show up in console logs at the beginning of each query execution....which seems like a bit much? 
* I noticed one obviously edge-direction-specific edge-attribute: CTKP's `subject_boxed_warning`. I think this refers to the chemical/intervention having a boxed warning. I think we can leave this alone for now. 
    * @gglusman Could this edge-attribute be renamed to something direction-agnostic like `drug_boxed_warning` or `intervention_boxed_warning`? It is also confusing because `subject` in clinical trials research can mean multiple things...

### And for the PRs...

I updated https://github.com/biothings/bte-server/pull/43 to uncomment Multiomics CTKP. 
Then I merged this `add-trapi-kps` stuff into https://github.com/biothings/bte-server/pull/44. So now the diff between 43 and 44 is that 44 has the new flag. 
I was trying to avoid merge conflicts, and I hope that works okay...

Also I made a PR for the upcoming semmeddb override https://github.com/biothings/bte-server/pull/45. That may have a merge conflict with 44.

**Comment by tokebe** [comment]
In my debug testing I was able to see that a query going to CTKP had multiple IDs on the node and results were still transformed correctly.

I've also pushed a change to the logging so it's just one line per KP.

**Comment by gglusman** [comment]
>   * @gglusman Could this edge-attribute be renamed to something direction-agnostic like `drug_boxed_warning` or `intervention_boxed_warning`? It is also confusing because `subject` in clinical trials research can mean multiple things...

Absolutely! I just released version 2.4.0 of CTKP, now using `intervention_boxed_warning`.

**Comment by colleenXu** [comment]
Current situation:
* we use overrides to remove the other clinical-trial-data-based operations. This is so their removal can be deployed in tandem with adding Multiomics CTKP to BTE's use. 
* For now, we're going to **keep those overrides (no hot-fixes)** AND **we aren't going to merge the [yaml changes](https://github.com/NCATS-Tangerine/translator-api-registry/pull/157)** into master 
    * wait until we know more about the next phase starting 12/2. Is Multiomics CTKP still around/active development? Does Translator still want us to use it exclusively for clinical trials info?

**Comment by tokebe** [comment]
Good to close?

**Comment by colleenXu** [comment]
This issue can be closed, but we'll want to remember the current situation ⏫ (previous post). 

The registered SmartAPI yamls for MyChem/repoDB still have the clinical-trial-based operations (master branch). 

All instances of BTE are currently using the overrides to the [remove-clinical-trials branch](https://github.com/NCATS-Tangerine/translator-api-registry/pull/157). 

We'll need to merge the yaml changes later if we still want to remove these operations from Translator use (without the override).

**Comment by colleenXu** [comment]
Update!

Yaml changes have been merged to master https://github.com/NCATS-Tangerine/translator-api-registry/pull/157 and merged into the [refactor](https://github.com/NCATS-Tangerine/translator-api-registry/commit/21281a26ade32b99a310607653a39b91f5410751) branch. 

Now the only thing hanging is removing the overrides so the old branches can be removed. See https://github.com/biothings/biothings_explorer/issues/811#issuecomment-2611858319 for details
